version: '3.8'

services:
  # Redis message broker
  redis:
    image: redis:7-alpine
    container_name: voice_assistant_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    
  # Voice Assistant main application
  voice_assistant:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: voice_assistant_main
    depends_on:
      - redis
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
      - /dev/snd:/dev/snd  # Audio devices
    devices:
      - /dev/snd  # Audio devices access
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NAVIDROME_USER=${NAVIDROME_USER:-admin}
      - NAVIDROME_PASS=${NAVIDROME_PASS:-password}
      - NAVIDROME_URL=${NAVIDROME_URL:-http://host.docker.internal:4533}
    restart: unless-stopped
    privileged: true  # Necessario per accesso audio
    network_mode: host  # Per accesso a dispositivi audio locali
    
  # Prometheus monitoring (opzionale)
  prometheus:
    image: prom/prometheus:latest
    container_name: voice_assistant_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    profiles: ["monitoring"]
    
  # Grafana dashboard (opzionale)
  grafana:
    image: grafana/grafana:latest
    container_name: voice_assistant_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    profiles: ["monitoring"]

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: voice_assistant_network

